### PR TITLE
Publish docker image also to DockerHub

### PR DESCRIPTION
**Pull request by glimchb**

### CODE REVIEW

**Comment by glimchb** [comment]
@stefanberger can you please check that "GitHub Actions" is enabled in `Settings` https://github.com/stefanberger/swtpm/settings/actions ?

**Comment by stefanberger** [comment]
> @stefanberger can you please check that `GitHub Actions` is enabled in `Settings` https://github.com/stefanberger/swtpm/settings/actions ?

Should all be enabled...

**Comment by glimchb** [comment]
@stefanberger my bad, I fixed it

1. default branch is `master` and not `main` - fixed and now actions triggered on push
2. docker build - removed ARM compile for now, so docker build will start passing now
3. thank you

**Comment by glimchb** [comment]
@stefanberger all ci passed, please merge

**Comment by glimchb** [comment]
Looks great and published to
- https://hub.docker.com/r/stefanberger/swtpm

**Comment by glimchb** [comment]
> Tanks for setting this up. I hope people are aware that what is being offered via docker hub are snapshot versions and not some sort of release versions. At some point we will have to switch to libtpms v0.10 (which is not done yet) rather than following master there as well...

when release is happening, we can then build docker in the release job and pass exact versions we want to build on both libtpm and swtpm

**Pull request merged**
