### PR TITLE
Add support for --print-capabilities command line option

### PR DESCRIPTION
**Pull request by stefanberger**
This series of patches adds support for the `--print-capabilities` command line option and addresses issue #143 .

### CODE REVIEW

**Comment by stefanberger** [comment]
@elmarco If you have time to review this series ...

**Comment by elmarco** [comment]
I think you could have saved quite a lot of code and a an extra depedency on json-c by using printf()....

**Comment by stefanberger** [comment]
> 
> 
> I think you could have saved quite a lot of code and a an extra depedency on json-c by using printf()....

I will remove it...

**Comment by stefanberger** [comment]
@elmarco Doing just string construction now.

**Comment by stefanberger** [comment]
Unless there are any more comments I'd merge early next week.

**Comment by elmarco** [comment]
lgtm

**Pull request merged**
